"""Tests generated by AMO Test Pilot for identity_mutation.py"""
import pytest
from app.models.world_state import WorldState, GeneralStatus
from app.models.world_state import GeneralEncounter as GE
from app.narrative.identity_mutation import (
    MUTATIONS,
    apply_mutation,
    check_empire_route,
    initiate_defector_arc,
    get_mutation_context,
)


@pytest.fixture
def world_state():
    ws = WorldState(empire_resonance=50, identity_anchor=50)
    ws.general_status = {
        "vorn": GeneralStatus(),
        "kha": GeneralStatus(),
        "mireth": GeneralStatus(),
        "azen": GeneralStatus(),
    }
    return ws


# ──────────────────────────────────────────────
# Mutation definitions
# ──────────────────────────────────────────────

def test_all_3_mutations_defined():
    assert "mirror_crack" in MUTATIONS
    assert "conversion" in MUTATIONS
    assert "resistant" in MUTATIONS


# ──────────────────────────────────────────────
# apply_mutation
# ──────────────────────────────────────────────

def test_apply_mirror_crack(world_state):
    result = apply_mutation(world_state, "mirror_crack")
    assert result is True
    assert world_state.world_flags.get("mutation_mirror_crack_active") is True

def test_apply_conversion(world_state):
    result = apply_mutation(world_state, "conversion")
    assert result is True
    assert world_state.empire_allegiance == "agent"
    assert world_state.empire_route_unlocked is True
    assert world_state.world_flags.get("mutation_conversion_active") is True
    assert world_state.world_flags.get("empire_route_active") is True

def test_apply_resistant(world_state):
    world_state.identity_anchor = 30
    result = apply_mutation(world_state, "resistant")
    assert result is True
    assert world_state.world_flags.get("mutation_resistant_active") is True
    assert world_state.identity_anchor == 50  # floor boost

def test_apply_resistant_keeps_high_anchor(world_state):
    world_state.identity_anchor = 80
    apply_mutation(world_state, "resistant")
    assert world_state.identity_anchor == 80  # no change, already above 50

def test_apply_unknown_mutation(world_state):
    result = apply_mutation(world_state, "unknown_mutation")
    assert result is False

def test_apply_mutation_dedup(world_state):
    """Dedup: mutation should not apply if already triggered in 2+ encounters."""
    # First encounter with mirror_crack — this is the "current" one
    world_state.general_encounters.append(GE(
        general_id="vorn", phase_reached=3, resolution="victory",
        mutation_triggered="mirror_crack",
    ))
    # Second encounter with mirror_crack — this is a PREVIOUS one
    world_state.general_encounters.append(GE(
        general_id="kha", phase_reached=3, resolution="victory",
        mutation_triggered="mirror_crack",
    ))
    result = apply_mutation(world_state, "mirror_crack")
    assert result is False  # already triggered in previous encounter


# ──────────────────────────────────────────────
# Empire Route
# ──────────────────────────────────────────────

def test_check_empire_route_not_eligible(world_state):
    result = check_empire_route(world_state)
    assert result["eligible"] is False
    assert result["active"] is False

def test_check_empire_route_eligible_at_80(world_state):
    world_state.empire_resonance = 80
    result = check_empire_route(world_state)
    assert result["eligible"] is True

def test_check_empire_route_active(world_state):
    world_state.world_flags["empire_route_active"] = True
    world_state.empire_allegiance = "agent"
    result = check_empire_route(world_state)
    assert result["active"] is True
    assert result["can_defect"] is True
    assert "Empire Agent" in result["status_description"]


# ──────────────────────────────────────────────
# Defector Arc
# ──────────────────────────────────────────────

def test_initiate_defector_arc_success(world_state):
    world_state.empire_allegiance = "agent"
    world_state.empire_resonance = 80
    result = initiate_defector_arc(world_state)
    assert result is True
    assert world_state.empire_allegiance == "defector"
    assert world_state.empire_resonance == 40  # 80 - 40
    assert world_state.world_flags.get("defector_fracture_mark") is True

def test_initiate_defector_arc_fails_if_not_agent(world_state):
    result = initiate_defector_arc(world_state)
    assert result is False
    assert world_state.empire_allegiance == "none"


# ──────────────────────────────────────────────
# LLM Context
# ──────────────────────────────────────────────

def test_get_mutation_context_empty(world_state):
    assert get_mutation_context(world_state) == ""

def test_get_mutation_context_mirror_crack(world_state):
    world_state.world_flags["mutation_mirror_crack_active"] = True
    ctx = get_mutation_context(world_state)
    assert "IDENTITY MUTATIONS" in ctx
    assert "Mirror Crack" in ctx

def test_get_mutation_context_empire_route(world_state):
    world_state.world_flags["empire_route_active"] = True
    world_state.empire_allegiance = "agent"
    ctx = get_mutation_context(world_state)
    assert "EMPIRE ROUTE ACTIVE" in ctx

def test_get_mutation_context_defector(world_state):
    world_state.world_flags["empire_route_active"] = True
    world_state.empire_allegiance = "defector"
    world_state.world_flags["defector_fracture_mark"] = True
    ctx = get_mutation_context(world_state)
    assert "DEFECTOR ARC" in ctx
    assert "fracture mark" in ctx
