"""Tests generated by AMO Test Pilot for villain_encounter.py"""
import pytest
from app.models.world_state import WorldState, GeneralStatus
from app.narrative.villain_encounter import (
    GENERAL_PROFILES,
    start_encounter,
    advance_encounter_phase,
    resolve_encounter,
    get_encounter_context,
    detect_general_in_prose,
)


@pytest.fixture
def world_state():
    ws = WorldState(empire_resonance=30, identity_anchor=50)
    ws.general_status = {
        "vorn": GeneralStatus(),
        "kha": GeneralStatus(),
        "mireth": GeneralStatus(),
        "azen": GeneralStatus(),
    }
    return ws


# ──────────────────────────────────────────────
# General Profiles
# ──────────────────────────────────────────────

def test_all_4_general_profiles_exist():
    assert len(GENERAL_PROFILES) == 4
    assert "vorn" in GENERAL_PROFILES
    assert "kha" in GENERAL_PROFILES
    assert "mireth" in GENERAL_PROFILES
    assert "azen" in GENERAL_PROFILES

def test_general_profile_has_unique_mechanic():
    mechanics = {p.mechanic for p in GENERAL_PROFILES.values()}
    assert mechanics == {"stability_test", "anti_free_zone", "memory_suppression", "forced_choice"}


# ──────────────────────────────────────────────
# Encounter lifecycle
# ──────────────────────────────────────────────

def test_start_encounter_success(world_state):
    result = start_encounter(world_state, "vorn", chapter=5)
    assert result is True
    assert world_state.active_general == "vorn"
    assert world_state.general_status["vorn"].encounter_phase == 1
    assert world_state.general_status["vorn"].status == "manifested"

def test_start_encounter_already_active(world_state):
    start_encounter(world_state, "vorn")
    result = start_encounter(world_state, "vorn")
    assert result is False

def test_start_encounter_invalid_id(world_state):
    result = start_encounter(world_state, "unknown_general")
    assert result is False

def test_advance_encounter_phase_to_2(world_state):
    start_encounter(world_state, "vorn")
    new_phase = advance_encounter_phase(world_state, "vorn", "understood")
    assert new_phase == 2
    assert world_state.general_status["vorn"].status == "confronted"

def test_advance_encounter_phase_rejected(world_state):
    start_encounter(world_state, "kha")
    advance_encounter_phase(world_state, "kha", "rejected_with_reason")
    assert world_state.identity_anchor == 58  # 50 + 8

def test_advance_encounter_phase_avoided_creates_tension(world_state):
    start_encounter(world_state, "mireth")
    advance_encounter_phase(world_state, "mireth", "avoided")
    assert "mireth" in world_state.unresolved_tensions

def test_advance_encounter_phase_caps_at_3(world_state):
    start_encounter(world_state, "azen")
    advance_encounter_phase(world_state, "azen")
    advance_encounter_phase(world_state, "azen")
    result = advance_encounter_phase(world_state, "azen")
    assert result == 3


# ──────────────────────────────────────────────
# Resolution
# ──────────────────────────────────────────────

def test_resolve_encounter_victory(world_state):
    start_encounter(world_state, "vorn")
    mutation = resolve_encounter(world_state, "vorn", "victory", chapter=10, last_words="test")
    assert world_state.general_status["vorn"].status == "defeated"
    assert world_state.general_status["vorn"].resolution == "victory"
    assert world_state.identity_anchor == 70  # 50 + 20
    assert len(world_state.general_encounters) == 1
    assert world_state.general_encounters[0].last_words == "test"

def test_resolve_encounter_alliance(world_state):
    start_encounter(world_state, "kha")
    resolve_encounter(world_state, "kha", "alliance")
    assert world_state.general_status["kha"].philosophy_absorbed is True
    assert len(world_state.absorbed_arguments) == 1

def test_resolve_encounter_stalemate_creates_tension(world_state):
    start_encounter(world_state, "mireth")
    resolve_encounter(world_state, "mireth", "stalemate")
    assert "mireth" in world_state.unresolved_tensions

def test_resolve_encounter_mirror_crack_mutation(world_state):
    world_state.empire_resonance = 25 
    start_encounter(world_state, "vorn")
    mutation = resolve_encounter(world_state, "vorn", "victory")
    assert mutation == "mirror_crack"
    assert world_state.world_flags.get("mutation_mirror_crack_active") is True

def test_resolve_encounter_resistant_not_overwrite_mirror_crack(world_state):
    """BUG 1 fix: resistant should NOT overwrite mirror_crack."""
    world_state.empire_resonance = 25
    world_state.identity_anchor = 70
    # First victory
    ws2 = world_state
    ws2.general_status["kha"].resolution = "victory"
    ws2.general_status["kha"].status = "defeated"
    # Second victory triggers mirror_crack but should NOT be overwritten by resistant
    start_encounter(ws2, "vorn")
    mutation = resolve_encounter(ws2, "vorn", "victory")
    assert mutation == "mirror_crack"  # NOT "resistant"

def test_resolve_encounter_clears_active_general(world_state):
    start_encounter(world_state, "azen")
    resolve_encounter(world_state, "azen", "victory")
    assert world_state.active_general == ""


# ──────────────────────────────────────────────
# LLM Context
# ──────────────────────────────────────────────

def test_get_encounter_context_empty_no_encounter(world_state):
    ctx = get_encounter_context(world_state)
    assert ctx == ""  # no active general, no echoes

def test_get_encounter_context_active_encounter(world_state):
    start_encounter(world_state, "vorn")
    ctx = get_encounter_context(world_state)
    assert "ACTIVE GENERAL ENCOUNTER" in ctx
    assert "Vorn" in ctx
    assert "VILLAIN DIALOGUE RULES" in ctx

def test_get_encounter_context_echoes_after_defeat(world_state):
    start_encounter(world_state, "vorn")
    resolve_encounter(world_state, "vorn", "victory", last_words="Phá hoại thôi sao?")
    ctx = get_encounter_context(world_state)
    assert "GENERAL ECHOES" in ctx
    assert "Phá hoại thôi sao?" in ctx


# ──────────────────────────────────────────────
# Prose detection
# ──────────────────────────────────────────────

def test_detect_general_in_prose_starts_encounter(world_state):
    detect_general_in_prose(world_state, "Tướng Vorn xuất hiện", chapter=10)
    assert world_state.active_general == "vorn"
    assert world_state.general_status["vorn"].encounter_phase == 1

def test_detect_general_in_prose_no_false_positive_kha(world_state):
    """BUG 3 fix: 'khả năng' should NOT trigger Kha encounter."""
    detect_general_in_prose(world_state, "Khả năng của player rất cao", chapter=10)
    assert world_state.active_general == ""
    assert world_state.general_status["kha"].encounter_phase == 0

def test_detect_general_in_prose_empty(world_state):
    detect_general_in_prose(world_state, "", chapter=10)
    assert world_state.active_general == ""
