"""Tests generated by AMO Test Pilot for emissary.py"""
import pytest
from app.models.world_state import WorldState, EmissaryStatus
from app.narrative.emissary import (
    EMISSARY_PROFILES,
    score_interaction,
    check_reveal_state,
    get_emissary_context,
    detect_emissary_in_prose,
)


@pytest.fixture
def world_state():
    ws = WorldState(empire_resonance=30, identity_anchor=50)
    ws.emissary_status = {
        "kaen": EmissaryStatus(sympathy_score=0),
        "sira": EmissaryStatus(sympathy_score=0),
        "thol": EmissaryStatus(sympathy_score=0),
    }
    return ws


# ──────────────────────────────────────────────
# Profiles
# ──────────────────────────────────────────────

def test_all_3_emissary_profiles_exist():
    assert "kaen" in EMISSARY_PROFILES
    assert "sira" in EMISSARY_PROFILES
    assert "thol" in EMISSARY_PROFILES

def test_emissary_profile_has_required_fields():
    for eid, p in EMISSARY_PROFILES.items():
        assert p.id == eid
        assert p.name
        assert p.cover_role
        assert p.true_role
        assert p.philosophy
        assert p.sympathy_trigger
        assert p.personality_tone


# ──────────────────────────────────────────────
# Interaction scoring
# ──────────────────────────────────────────────

def test_score_interaction_agreed_with_logic(world_state):
    result = score_interaction(world_state, "kaen", "agreed_with_logic", chapter=1)
    assert result == 15  # 0 + 15
    assert world_state.emissary_status["kaen"].sympathy_score == 15

def test_score_interaction_strong_rejection(world_state):
    world_state.emissary_status["sira"].sympathy_score = 20
    result = score_interaction(world_state, "sira", "strong_rejection", chapter=2)
    assert result == 5  # 20 - 15
    assert world_state.identity_anchor == 60  # 50 + 10

def test_score_interaction_unknown_emissary(world_state):
    result = score_interaction(world_state, "unknown_npc", "agreed_with_logic")
    assert result == 0

def test_score_interaction_logs_emissary_interaction(world_state):
    score_interaction(world_state, "thol", "showed_understanding", chapter=3)
    assert len(world_state.emissary_interactions) == 1
    record = world_state.emissary_interactions[0]
    assert record.emissary_id == "thol"
    assert record.sympathy_delta == 8
    assert record.chapter == 3

def test_score_interaction_clamps_sympathy_to_100(world_state):
    world_state.emissary_status["kaen"].sympathy_score = 95
    result = score_interaction(world_state, "kaen", "agreed_with_logic")
    assert result == 100  # clamped

def test_score_interaction_clamps_sympathy_to_0(world_state):
    world_state.emissary_status["kaen"].sympathy_score = 5
    result = score_interaction(world_state, "kaen", "strong_rejection")
    assert result == 0  # clamped


# ──────────────────────────────────────────────
# Reveal logic
# ──────────────────────────────────────────────

def test_check_reveal_state_hidden(world_state):
    level, desc = check_reveal_state(world_state, "kaen")
    assert level == "hidden"

def test_check_reveal_state_subtle_hints(world_state):
    world_state.emissary_status["kaen"].sympathy_score = 25
    level, _ = check_reveal_state(world_state, "kaen")
    assert level == "subtle_hints"

def test_check_reveal_state_crisis_reveal(world_state):
    world_state.emissary_status["sira"].sympathy_score = 55
    level, _ = check_reveal_state(world_state, "sira")
    assert level == "crisis_reveal"

def test_check_reveal_state_full_reveal(world_state):
    world_state.emissary_status["thol"].sympathy_score = 85
    level, _ = check_reveal_state(world_state, "thol")
    assert level == "full_reveal"

def test_check_reveal_state_unknown_emissary(world_state):
    level, _ = check_reveal_state(world_state, "unknown")
    assert level == "hidden"


# ──────────────────────────────────────────────
# LLM Context
# ──────────────────────────────────────────────

def test_get_emissary_context_empty_for_low_sympathy(world_state):
    assert get_emissary_context(world_state) == ""

def test_get_emissary_context_shows_near_reveal(world_state):
    world_state.emissary_status["kaen"].sympathy_score = 55
    ctx = get_emissary_context(world_state)
    assert "EMISSARY TRACKING" in ctx
    assert "Kaen" in ctx
    assert "sắp reveal" in ctx

def test_get_emissary_context_shows_revealed(world_state):
    world_state.emissary_status["sira"].revealed_to_player = True
    ctx = get_emissary_context(world_state)
    assert "REVEALED" in ctx
    assert "Sira" in ctx

def test_get_emissary_context_shows_allegiance_offered(world_state):
    world_state.emissary_status["kaen"].revealed_to_player = True
    world_state.emissary_status["kaen"].allegiance_offered = True
    ctx = get_emissary_context(world_state)
    assert "Empire allegiance" in ctx


# ──────────────────────────────────────────────
# Prose detection
# ──────────────────────────────────────────────

def test_detect_emissary_in_prose_positive(world_state):
    detect_emissary_in_prose(world_state, "Player đồng ý với Kaen", chapter=5)
    assert world_state.emissary_status["kaen"].sympathy_score == 8  # showed_understanding

def test_detect_emissary_in_prose_negative(world_state):
    detect_emissary_in_prose(world_state, "Player từ chối Sira", chapter=5)
    assert world_state.emissary_status["sira"].sympathy_score == 0  # 0 - 5 clamped to 0

def test_detect_emissary_in_prose_empty(world_state):
    detect_emissary_in_prose(world_state, "", chapter=5)
    # No change
    assert world_state.emissary_status["kaen"].sympathy_score == 0
