"""Amoisekai — Growth × Narrative Orchestration.

Connects growth triggers to narrative beat injection.
When a Unique Skill reaches a growth threshold (Bloom/Aspect/Ultimate),
this module generates narrative beats that inject into the Planner pipeline.

The orchestrator calls `check_and_inject_growth_beats()` per scene,
which returns any growth-related beats to prepend/append to the plan.

Ref: UNIQUE_SKILL_GROWTH_SPEC v1.1 §6.5, §7.3, §11.2
"""

from __future__ import annotations

import logging
from enum import Enum
from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from app.models.player import PlayerState

logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════
# GROWTH BEAT TYPES
# ══════════════════════════════════════════════

class GrowthArcType(str, Enum):
    """Type of growth narrative arc."""
    ECHO = "echo"           # 1-scene subtle refinement
    SCAR = "scar"           # 2-scene trauma adaptation
    ASPECT_FORGE = "aspect_forge"  # 3-scene branching arc
    ULTIMATE = "ultimate"   # 3-scene Season Climax arc


class GrowthBeat(BaseModel):
    """A narrative beat generated by growth triggers.

    Injected into the Planner's beat list during chapter planning.
    """
    arc_type: str = ""           # GrowthArcType value
    beat_number: int = 1         # Position within the arc
    total_beats: int = 1         # Total beats in this arc
    scene_type: str = "exploration"  # Scene type for this beat
    title: str = ""              # Beat title for Planner
    description: str = ""        # Beat description for Writer
    priority: str = "medium"     # "medium" | "high" | "critical"
    is_decision_point: bool = False  # Requires player choice
    decision_choices: list[dict] = Field(default_factory=list)  # Choice options
    growth_context: dict = Field(default_factory=dict)  # Extra data for Writer
    writer_instruction: str = ""  # Direct instruction for SceneWriter


# ══════════════════════════════════════════════
# BLOOM (ECHO/SCAR) BEATS
# ══════════════════════════════════════════════

def build_bloom_beats(
    player: PlayerState,
    bloom_trigger: dict,
) -> list[GrowthBeat]:
    """Build beats for Bloom event (Echo Deepening or Scar Adaptation).

    Echo = 1 scene (subtle, rest/exploration).
    Scar = 2 scenes (trauma reveal + adaptation).
    """
    growth = player.unique_skill_growth
    skill = player.unique_skill
    if not growth or not skill:
        return []

    bloom_path = bloom_trigger.get("bloom_path", "echo")

    if bloom_path == "scar":
        return [
            GrowthBeat(
                arc_type=GrowthArcType.SCAR,
                beat_number=1,
                total_beats=2,
                scene_type="exploration",
                title="Vết Thương Thức Tỉnh",
                description=(
                    f"Unique Skill '{skill.name}' phản ứng bất thường sau trận chiến. "
                    "Trauma trước đây đang làm skill biến đổi — player cảm nhận "
                    "sức mạnh mới nhưng đau đớn. Mô tả skill đang 'thở' theo vết sẹo."
                ),
                priority="high",
                writer_instruction=(
                    f"Unique Skill '{skill.name}' đang trải qua Scar Adaptation. "
                    "Skill biến đổi từ trauma — mô tả quá trình đau đớn nhưng mạnh mẽ hơn. "
                    "Đây KHÔNG phải tiến hóa bình thường — đây là sẹo hóa thành sức mạnh."
                ),
                growth_context={
                    "event": "scar_bloom",
                    "bloom_path": "scar",
                    "skill_name": skill.name,
                    "scar_type": getattr(growth, "scar_type", ""),
                },
            ),
            GrowthBeat(
                arc_type=GrowthArcType.SCAR,
                beat_number=2,
                total_beats=2,
                scene_type="exploration",
                title="Sẹo Thành Giáp",
                description=(
                    f"Skill '{skill.name}' hoàn thành Scar Adaptation. "
                    "Vết thương trở thành phần cốt lõi. "
                    "Player chấp nhận trauma → skill tiến hóa."
                ),
                priority="high",
                writer_instruction=(
                    f"Bloom hoàn thành via Scar path. '{skill.name}' giờ mang dấu ấn "
                    "của trải nghiệm đau thương. Mô tả cinematic moment khi skill 'chấp nhận vết sẹo'."
                ),
                growth_context={
                    "event": "scar_bloom_complete",
                    "bloom_path": "scar",
                    "skill_name": skill.name,
                },
            ),
        ]

    # Echo Deepening — 1 scene, subtle
    return [
        GrowthBeat(
            arc_type=GrowthArcType.ECHO,
            beat_number=1,
            total_beats=1,
            scene_type="rest",
            title="Tiếng Vọng Sâu",
            description=(
                f"Unique Skill '{skill.name}' phản ánh identity chủ nhân rõ hơn. "
                "Trong khoảnh khắc yên tĩnh, player nhận ra skill đang "
                "'lớn lên' cùng mình. Mô tả subtle refinement — không flashy."
            ),
            priority="medium",
            writer_instruction=(
                f"Echo Deepening cho '{skill.name}'. Skill tinh chỉnh theo identity — "
                "mô tả subtle moment khi player nhận ra skill 'hiểu' mình hơn. "
                "Đây là growth tự nhiên, KHÔNG phải power-up."
            ),
            growth_context={
                "event": "echo_bloom",
                "bloom_path": "echo",
                "skill_name": skill.name,
                "echo_coherence_streak": getattr(growth, "echo_coherence_streak", 0),
            },
        ),
    ]


# ══════════════════════════════════════════════
# ASPECT FORGE ARC (3 SCENES)
# ══════════════════════════════════════════════

def build_aspect_forge_beats(
    player: PlayerState,
    aspect_a_name: str = "Tường Minh",
    aspect_a_description: str = "Thấy TẤT CẢ dù chỉ bề mặt",
    aspect_b_name: str = "Phá Chấp",
    aspect_b_description: str = "Biết TRIỆT ĐỂ dù chỉ một điều",
) -> list[GrowthBeat]:
    """Build 3-beat Aspect Forge narrative arc.

    Scene 1: "Skill Run" — discovery, skill activating abnormally
    Scene 2: "The Fork" — decision point with 3 choices (A / B / Defer)
    Scene 3: "Reborn" — resolution, new aspect applied
    """
    skill = player.unique_skill
    if not skill:
        return []

    return [
        # ── Scene 1: Skill Run ──
        GrowthBeat(
            arc_type=GrowthArcType.ASPECT_FORGE,
            beat_number=1,
            total_beats=3,
            scene_type="exploration",
            title="Skill Run",
            description=(
                f"Unique Skill '{skill.name}' kích hoạt bất thường — mạnh hơn bình thường "
                "nhưng không kiểm soát được. Skill phát sáng, rung lắc, muốn THAY ĐỔI. "
                "Player cảm nhận skill đang ở ngưỡng tiến hóa."
            ),
            priority="critical",
            writer_instruction=(
                f"'{skill.name}' đang ở ngưỡng Aspect Forge. Mô tả skill hoạt động "
                "bất thường — mạnh hơn nhưng unstable. Đây là khởi đầu của 3-scene arc. "
                "Tạo tension: skill MUỐN tiến hóa, player chưa sẵn sàng."
            ),
            growth_context={
                "event": "aspect_forge_start",
                "skill_name": skill.name,
                "arc_position": "1/3",
            },
        ),

        # ── Scene 2: The Fork (Decision Point) ──
        GrowthBeat(
            arc_type=GrowthArcType.ASPECT_FORGE,
            beat_number=2,
            total_beats=3,
            scene_type="exploration",
            title="The Fork",
            description=(
                f"Skill '{skill.name}' buộc kích hoạt max. Skill 'phân nhánh' — "
                "player thấy 2 vision: một con đường rộng mở, một con đường sâu hun hút. "
                "DECISION POINT — player phải chọn hướng tiến hóa."
            ),
            priority="critical",
            is_decision_point=True,
            decision_choices=[
                {
                    "id": "aspect_a",
                    "text": f"🌐 Chọn {aspect_a_name} — \"{aspect_a_description}\"",
                    "risk_level": 5,
                    "consequence_hint": f"Skill tiến hóa thành {aspect_a_name}",
                },
                {
                    "id": "aspect_b",
                    "text": f"🎯 Chọn {aspect_b_name} — \"{aspect_b_description}\"",
                    "risk_level": 5,
                    "consequence_hint": f"Skill tiến hóa thành {aspect_b_name}",
                },
                {
                    "id": "aspect_defer",
                    "text": "⏸️ Trì hoãn — \"Bạn chưa sẵn sàng\"",
                    "risk_level": 2,
                    "consequence_hint": "Aspect Forge hoãn lại 5 chapters",
                },
            ],
            writer_instruction=(
                f"QUYẾT ĐỊNH LỚN: '{skill.name}' đang phân nhánh. "
                f"Vision A → {aspect_a_name}: {aspect_a_description}. "
                f"Vision B → {aspect_b_name}: {aspect_b_description}. "
                "Mô tả 2 vision rõ ràng, epic, contrasting. "
                "Đây là permanent choice — KHÔNG thể đổi."
            ),
            growth_context={
                "event": "aspect_forge_fork",
                "skill_name": skill.name,
                "arc_position": "2/3",
                "aspect_a": aspect_a_name,
                "aspect_b": aspect_b_name,
            },
        ),

        # ── Scene 3: Reborn ──
        GrowthBeat(
            arc_type=GrowthArcType.ASPECT_FORGE,
            beat_number=3,
            total_beats=3,
            scene_type="exploration",
            title="Reborn",
            description=(
                f"Skill '{skill.name}' hoàn thành tiến hóa Aspect. "
                "Cinematic transformation — skill mới lần đầu kích hoạt. "
                "Player sở hữu sức mạnh hoàn toàn mới."
            ),
            priority="critical",
            writer_instruction=(
                "Aspect Forge HOÀN THÀNH. Mô tả cinematic moment: "
                "skill cũ tan biến, skill mới hiện ra. First use ngay trong scene. "
                "\"Bạn không còn sở hữu [tên cũ]. Giờ bạn sở hữu [tên mới].\""
            ),
            growth_context={
                "event": "aspect_forge_complete",
                "skill_name": skill.name,
                "arc_position": "3/3",
            },
        ),
    ]


# ══════════════════════════════════════════════
# ULTIMATE SYNTHESIS ARC (3 SCENES)
# ══════════════════════════════════════════════

def build_ultimate_beats(
    player: PlayerState,
    absorbed_skill_name: str = "",
) -> list[GrowthBeat]:
    """Build 3-beat Ultimate Synthesis narrative arc (Season Climax).

    Scene 1: "Giới Hạn" — losing boss fight
    Scene 2: "Cộng Hưởng Tuyệt Đối" — resonance + synthesis
    Scene 3: "Tái Sinh" — Ultimate first activation
    """
    skill = player.unique_skill
    if not skill:
        return []

    skill_name = skill.name
    growth = player.unique_skill_growth
    aspect = getattr(growth, "aspect_chosen", "") if growth else ""

    return [
        # ── Scene 1: Giới Hạn ──
        GrowthBeat(
            arc_type=GrowthArcType.ULTIMATE,
            beat_number=1,
            total_beats=3,
            scene_type="combat",
            title="Giới Hạn",
            description=(
                "Season Climax boss, phase 3 — player đang thua. "
                f"Unique Skill '{skill_name}' (Aspect: {aspect}) kích hoạt max → KHÔNG ĐỦ. "
                f"Normal skill '{absorbed_skill_name}' cũng max → KHÔNG ĐỦ. "
                "Hai sức mạnh song song nhưng tách rời. Bạn thiếu gì đó."
            ),
            priority="critical",
            writer_instruction=(
                "Season Climax moment. Player ĐANG THUA. Cả Unique Skill lẫn Normal Skill "
                "đều đã dùng hết sức — vẫn không đủ. Mô tả desperation, "
                "nhưng KHÔNG cho player chết. Tạo tension cho synthesis."
            ),
            growth_context={
                "event": "ultimate_limit",
                "skill_name": skill_name,
                "absorbed_skill": absorbed_skill_name,
                "arc_position": "1/3",
            },
        ),

        # ── Scene 2: Cộng Hưởng Tuyệt Đối ──
        GrowthBeat(
            arc_type=GrowthArcType.ULTIMATE,
            beat_number=2,
            total_beats=3,
            scene_type="combat",
            title="Cộng Hưởng Tuyệt Đối",
            description=(
                "evolution_hint vang lên lần cuối — giọng nói từ khi sinh ra tại Void Between. "
                f"Unique Skill + '{absorbed_skill_name}' bắt đầu RESONANCE. "
                f"Normal skill bị ABSORB — biến mất khỏi equipped list. "
                "AI Forge gọi lần CUỐI → generate Ultimate Skill. NAMING EVENT."
            ),
            priority="critical",
            writer_instruction=(
                "Synthesis moment — hai sức mạnh hợp nhất. "
                f"'{absorbed_skill_name}' bị hấp thụ vào '{skill_name}'. "
                "Tên mới xuất hiện: format \"[Tên Skill] — [Danh xưng]\". "
                "Tất cả growth trước (Echo, Scar) integrate vào Ultimate."
            ),
            growth_context={
                "event": "ultimate_synthesis",
                "skill_name": skill_name,
                "absorbed_skill": absorbed_skill_name,
                "arc_position": "2/3",
            },
        ),

        # ── Scene 3: Tái Sinh ──
        GrowthBeat(
            arc_type=GrowthArcType.ULTIMATE,
            beat_number=3,
            total_beats=3,
            scene_type="combat",
            title="Tái Sinh",
            description=(
                "Ultimate Skill kích hoạt LẦN ĐẦU. "
                "Boss fight resolution — player thắng bằng Ultimate. "
                "ULTIMATE ABILITY lần đầu — cinematic moment kinh điển. "
                "Season Climax → kết thúc Season 1."
            ),
            priority="critical",
            writer_instruction=(
                "Ultimate Skill FIRST ACTIVATION. Mô tả cinematic combat moment: "
                "skill mới phát huy sức mạnh vượt trội. Boss bị defeated. "
                "Đây là peak moment của toàn bộ Season — make it EPIC."
            ),
            growth_context={
                "event": "ultimate_first_use",
                "skill_name": skill_name,
                "arc_position": "3/3",
            },
        ),
    ]


# ══════════════════════════════════════════════
# ASPECT DEFER TRACKING
# ══════════════════════════════════════════════

DEFER_CHAPTERS = 5  # Chapters until aspect forge re-triggers


def handle_aspect_defer(player: PlayerState) -> None:
    """Mark aspect forge as deferred. Re-triggers after 5 chapters."""
    growth = player.unique_skill_growth
    if not growth:
        return
    growth.aspect_deferred = True
    growth.aspect_defer_chapter = player.total_chapters
    logger.info(f"Aspect Forge deferred at chapter {player.total_chapters}. "
                f"Will re-trigger after {DEFER_CHAPTERS} more chapters.")


def is_aspect_defer_expired(player: PlayerState) -> bool:
    """Check if defer period (5 chapters) has passed."""
    growth = player.unique_skill_growth
    if not growth or not growth.aspect_deferred:
        return False
    return player.total_chapters >= growth.aspect_defer_chapter + DEFER_CHAPTERS


# ══════════════════════════════════════════════
# MAIN INTEGRATION: CHECK & INJECT
# ══════════════════════════════════════════════

def check_and_inject_growth_beats(
    player: PlayerState,
    growth_events: dict,
) -> list[GrowthBeat]:
    """Main entry point: check growth events and generate beats to inject.

    Called by orchestrator during chapter planning or per-scene.
    Returns list of GrowthBeats to inject into the narrative plan.

    Args:
        player: Current player state
        growth_events: Dict from update_growth_per_scene (contains
            bloom_ready, aspect_ready, ultimate_ready flags)

    Returns:
        List of GrowthBeat objects, empty if no growth event triggered.
    """
    beats: list[GrowthBeat] = []

    if not player.unique_skill or not player.unique_skill_growth:
        return beats

    # ── Ultimate (highest priority) ──
    if growth_events.get("ultimate_ready"):
        absorbed = _find_absorbable_skill(player)
        absorbed_name = absorbed.get("name", "") if absorbed else ""
        beats = build_ultimate_beats(player, absorbed_skill_name=absorbed_name)
        logger.info(f"Injecting Ultimate Synthesis arc ({len(beats)} beats)")
        return beats  # Ultimate takes over the entire chapter

    # ── Aspect Forge ──
    if growth_events.get("aspect_ready"):
        # Check if deferred and still waiting
        growth = player.unique_skill_growth
        if growth.aspect_deferred and not is_aspect_defer_expired(player):
            logger.info(
                f"Aspect Forge still deferred "
                f"({player.total_chapters - growth.aspect_defer_chapter}/{DEFER_CHAPTERS} chapters)"
            )
            return beats  # Still waiting

        beats = build_aspect_forge_beats(player)
        logger.info(f"Injecting Aspect Forge arc ({len(beats)} beats)")
        return beats  # Aspect takes full chapter

    # ── Bloom (Echo / Scar) ──
    bloom_trigger = growth_events.get("bloom_ready")
    if bloom_trigger:
        beats = build_bloom_beats(player, bloom_trigger)
        logger.info(f"Injecting Bloom beats ({len(beats)} beats)")
        return beats

    return beats


def build_growth_writer_context(player: PlayerState) -> dict:
    """Build growth context for SceneWriter.

    Provides Writer with current growth state data for accurate
    skill descriptions. Always included when player has unique skill.
    """
    skill = player.unique_skill
    growth = player.unique_skill_growth
    if not skill or not growth:
        return {}

    return {
        "unique_skill": {
            "name": skill.name,
            "mechanic": skill.mechanic,
            "category": skill.category,
        },
        "growth_state": {
            "type": growth.active_growth.value if hasattr(growth.active_growth, "value") else str(growth.active_growth),
            "current_stage": growth.current_stage,
            "echo_coherence_streak": growth.echo_coherence_streak,
            "scar_type": growth.scar_type.value if growth.scar_type and hasattr(growth.scar_type, "value") else None,
            "aspect": growth.aspect_chosen if growth.aspect_forged else None,
            "ultimate": bool(growth.ultimate_forged),
            "bloom_completed": growth.bloom_completed,
        },
        "instruction": (
            f"Mô tả unique skill '{skill.name}' ở dạng hiện tại. "
            f"Growth stage: {growth.current_stage}. "
            "Skill phản ánh hành trình player — không generic."
        ),
    }


# ══════════════════════════════════════════════
# HELPERS
# ══════════════════════════════════════════════

def _find_absorbable_skill(player: PlayerState) -> dict | None:
    """Find a normal skill that can be absorbed for Ultimate Synthesis.

    Requirements (from GROWTH_SPEC §7.2):
    - Not the unique skill itself
    - Refined (in progression.refinements_done)
    - Same principle as unique skill
    """
    if not player.unique_skill:
        return None

    unique_traits = set(player.unique_skill.trait_tags or [])
    refinements = set(getattr(player.progression, "refinements_done", []))

    for s in player.equipped_skills:
        if not isinstance(s, dict):
            continue
        skill_id = s.get("id", s.get("name", ""))
        if skill_id == player.unique_skill.name:
            continue  # Skip unique skill itself
        principle = s.get("primary_principle", "")
        if skill_id in refinements and principle in unique_traits:
            return s

    # Fallback: take first equipped normal skill if any
    for s in player.equipped_skills:
        if isinstance(s, dict) and s.get("name", "") != player.unique_skill.name:
            return s

    return None
